-- Capture run of script in file called custorders_schema_output.txt
set echo on
SPOOL oo_schema_output.txt

--student id: 35400145
--student name: Tan Siew Quin

-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-02 13:54:03 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE ADDRESS CASCADE CONSTRAINTS 
;

DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE COUNTRY CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE ITINERARY CASCADE CONSTRAINTS 
;

DROP TABLE MANIFEST CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE PORT CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ADDRESS 
    ( 
     addr_id       NUMBER (7)  NOT NULL , 
     addr_street   VARCHAR2 (30)  NOT NULL , 
     addr_town     VARCHAR2 (30)  NOT NULL , 
     addr_postcode VARCHAR2 (10)  NOT NULL , 
     country_code  CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ADDRESS.addr_id IS 'A surrogate key' 
;

COMMENT ON COLUMN ADDRESS.addr_street IS 'The street name of the address.' 
;

COMMENT ON COLUMN ADDRESS.addr_town IS 'The town name of the address.' 
;

COMMENT ON COLUMN ADDRESS.addr_postcode IS 'The postcode of the address.' 
;

COMMENT ON COLUMN ADDRESS.country_code IS 'The code of a country.' 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_PK PRIMARY KEY ( addr_id ) ;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_NK UNIQUE ( addr_street , addr_town , addr_postcode , country_code ) ;

CREATE TABLE CABIN 
    ( 
     cabin_no         VARCHAR2 (3)  NOT NULL , 
     ship_code        VARCHAR2 (7)  NOT NULL , 
     cabin_sleep_capa NUMBER (2)  NOT NULL , 
     cabin_class      CHAR (1)  NOT NULL 
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT chk_cabin_class 
    CHECK (cabin_class IN ('B', 'I', 'O', 'S')) 
;

COMMENT ON COLUMN CABIN.cabin_no IS 'Cabin number of the cabin.' 
;

COMMENT ON COLUMN CABIN.ship_code IS 'The code of the ship.' 
;

COMMENT ON COLUMN CABIN.cabin_sleep_capa IS 'The sleeping capacity of a cabin.' 
;

COMMENT ON COLUMN CABIN.cabin_class IS 'Class of the cabin which is either ''I'' for '' Interior'', ''O'' for ''Ocean view'', ''B'' for  ''Balcony'' or ''S'' for '' Suite''.' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_no, ship_code ) ;

CREATE TABLE COUNTRY 
    ( 
     country_code CHAR (3)  NOT NULL , 
     country_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COUNTRY.country_code IS 'The code of a country.' 
;

COMMENT ON COLUMN COUNTRY.country_name IS 'The name of a country.' 
;

ALTER TABLE COUNTRY 
    ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( country_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id              NUMBER (4)  NOT NULL , 
     cruise_name            VARCHAR2 (50)  NOT NULL , 
     cruise_desc            VARCHAR2 (50)  NOT NULL , 
     cruise_depart_dt       DATE  NOT NULL , 
     cruise_cost_per_person NUMBER (6,2)  NOT NULL , 
     ship_code              VARCHAR2 (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'Cruise ID identifies each cruise on a particular ship.' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'Name of the cruise.' 
;

COMMENT ON COLUMN CRUISE.cruise_desc IS 'Description of the cruise.' 
;

COMMENT ON COLUMN CRUISE.cruise_depart_dt IS 'The departure time of a cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_cost_per_person IS 'The cost of a cruise per person' 
;

COMMENT ON COLUMN CRUISE.ship_code IS 'The code of the ship.' 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE ITINERARY 
    ( 
     itinerary_dep_arr_datetime DATE  NOT NULL , 
     cruise_id                  NUMBER (4)  NOT NULL , 
     itinerary_dep_arr_status   CHAR (1)  NOT NULL , 
     port_code                  CHAR (5)  NOT NULL 
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT chk_depart_arr_status 
    CHECK (itinerary_dep_arr_status IN ('A', 'D')) 
;

COMMENT ON COLUMN ITINERARY.itinerary_dep_arr_datetime IS 'Records the departure/ arrival datetime of a cruise' 
;

COMMENT ON COLUMN ITINERARY.cruise_id IS 'Cruise ID identifies each cruise on a particular ship.' 
;

COMMENT ON COLUMN ITINERARY.itinerary_dep_arr_status IS 'Records the travel status of a cruise which is ''D'' for  ''Depart'' or''A'' for  ''Arrive''' 
;

COMMENT ON COLUMN ITINERARY.port_code IS 'The code of the port.' 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT ITENERARY_PK PRIMARY KEY ( cruise_id, itinerary_dep_arr_datetime ) ;

CREATE TABLE MANIFEST 
    ( 
     passenger_id         NUMBER (7)  NOT NULL , 
     cruise_id            NUMBER (4)  NOT NULL , 
     manifest_boarding_dt DATE , 
     cabin_no             VARCHAR2 (3)  NOT NULL , 
     ship_code            VARCHAR2 (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN MANIFEST.passenger_id IS 'The ID of the passenger who made their cruise booking.' 
;

COMMENT ON COLUMN MANIFEST.cruise_id IS 'Cruise ID identifies each cruise on a particular ship.' 
;

COMMENT ON COLUMN MANIFEST.manifest_boarding_dt IS 'The boarding date time of passenger when they board the ship' 
;

COMMENT ON COLUMN MANIFEST.cabin_no IS 'Cabin number of the cabin.' 
;

COMMENT ON COLUMN MANIFEST.ship_code IS 'The code of the ship.' 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT MANIFEST_PK PRIMARY KEY ( passenger_id, cruise_id ) ;

CREATE TABLE OPERATOR 
    ( 
     operator_id       NUMBER (7)  NOT NULL , 
     operator_name     VARCHAR2 (50)  NOT NULL , 
     operator_ceo_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OPERATOR.operator_id IS 'The operator ID.' 
;

COMMENT ON COLUMN OPERATOR.operator_name IS 'The name of the operator company.' 
;

COMMENT ON COLUMN OPERATOR.operator_ceo_name IS 'The name of the operator CEO.' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( operator_id ) ;

CREATE TABLE PASSENGER 
    ( 
     passenger_id       NUMBER (7)  NOT NULL , 
     passenger_fname    VARCHAR2 (25) , 
     passenger_lname    VARCHAR2 (25) , 
     passenger_gender   CHAR (1)  NOT NULL , 
     passenger_dob      DATE  NOT NULL , 
     passenger_phone    VARCHAR2 (15) , 
     passenger_guard_id NUMBER (7) , 
     addr_id            NUMBER (7)  NOT NULL 
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT chk_gender 
    CHECK (passenger_gender IN ('F', 'M', 'N')) 
;

COMMENT ON COLUMN PASSENGER.passenger_id IS 'The ID of the passenger who made their cruise booking.' 
;

COMMENT ON COLUMN PASSENGER.passenger_fname IS 'First name of the passenger.' 
;

COMMENT ON COLUMN PASSENGER.passenger_lname IS 'Last name of the passenger.' 
;

COMMENT ON COLUMN PASSENGER.passenger_gender IS 'Record the gender of passenger as ''F'' for ''Female'', ''M'' for ''Male'' and ''N'' for ''Prefer not to say''.' 
;

COMMENT ON COLUMN PASSENGER.passenger_dob IS 'Passenger''s date of birth.' 
;

COMMENT ON COLUMN PASSENGER.passenger_phone IS 'The phone number of passengers who are above 18 years old' 
;

COMMENT ON COLUMN PASSENGER.passenger_guard_id IS 'The ID of the passenger who made their cruise booking.' 
;

COMMENT ON COLUMN PASSENGER.addr_id IS 'A surrogate key' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( passenger_id ) ;

CREATE TABLE PORT 
    ( 
     port_code      CHAR (5)  NOT NULL , 
     port_name      VARCHAR2 (50)  NOT NULL , 
     port_latitude  NUMBER (8,6)  NOT NULL , 
     port_longitude NUMBER (9,6)  NOT NULL , 
     country_code   CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PORT.port_code IS 'The code of the port.' 
;

COMMENT ON COLUMN PORT.port_name IS 'The name of the port.' 
;

COMMENT ON COLUMN PORT.port_latitude IS 'The latitude of the port.' 
;

COMMENT ON COLUMN PORT.port_longitude IS 'The longitude of the port.' 
;

COMMENT ON COLUMN PORT.country_code IS 'The code of a country.' 
;

ALTER TABLE PORT 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( port_code ) ;

CREATE TABLE SHIP 
    ( 
     ship_code           VARCHAR2 (7)  NOT NULL , 
     ship_name           VARCHAR2 (50)  NOT NULL , 
     ship_comission_date DATE  NOT NULL , 
     ship_tonnage        NUMBER (8,2)  NOT NULL , 
     ship_max_guest_capa NUMBER (5)  NOT NULL , 
     operator_id         NUMBER (7)  NOT NULL , 
     country_code        CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_code IS 'The code of the ship.' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'The name of the ship.' 
;

COMMENT ON COLUMN SHIP.ship_comission_date IS 'The date the ship was comissioned' 
;

COMMENT ON COLUMN SHIP.ship_tonnage IS 'The tonnage of the ship.' 
;

COMMENT ON COLUMN SHIP.ship_max_guest_capa IS 'The ship''s maximum passenger capacity.' 
;

COMMENT ON COLUMN SHIP.operator_id IS 'The operator ID.' 
;

COMMENT ON COLUMN SHIP.country_code IS 'The code of a country.' 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_code ) ;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT address_passenger_fk FOREIGN KEY 
    ( 
     addr_id
    ) 
    REFERENCES ADDRESS 
    ( 
     addr_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cabin_manifest_fk FOREIGN KEY 
    ( 
     cabin_no,
     ship_code
    ) 
    REFERENCES CABIN 
    ( 
     cabin_no,
     ship_code
    ) 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT country_addr_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE PORT 
    ADD CONSTRAINT country_port_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT country_ship_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT cruise_itenenary_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cruise_manifest_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT operator_ship_fk FOREIGN KEY 
    ( 
     operator_id
    ) 
    REFERENCES OPERATOR 
    ( 
     operator_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT passenger_manifest_fk FOREIGN KEY 
    ( 
     passenger_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT passenger_passenger_fk FOREIGN KEY 
    ( 
     passenger_guard_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT port_itenenary_fk FOREIGN KEY 
    ( 
     port_code
    ) 
    REFERENCES PORT 
    ( 
     port_code
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT ship_cabin_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT ship_cruise_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off